export const allEvents = [
    {
      id: 1,
      employeeId: 1,
      title: 'Personal care',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      start: '12:00PM',
      end: '3:00PM',
      date: '2025-01-07',
    },
    {
      id: 2,
      employeeId: 2,
      title: 'Head Office',
      start: '2:00AM',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      end: '8:00AM',
      date: '2025-01-11',
    },
    {
      id: 3,
      employeeId: 3,
      title: 'Safe',
      start: '1:30PM',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      end: '4:30PM',
      date: '2025-01-07',
    },
    {
      id: 4,
      employeeId: 4,
      title: 'Shift',
      start: '11:00AM',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      end: '12:00PM',
      date: '2025-01-09',
    },
    {
      id: 5,
      employeeId: 5,
      title: 'Meeting',
      start: '12:00PM',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      end: '3PM',
      date: '2025-01-07',
    },
    {
      id: 5,
      employeeId: 5,
      title: 'Safety Measure',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      start: '12:00PM',
      end: '3PM',
      date: '2025-01-07',
    },
    {
      id: 5,
      employeeId: 5,
      title: 'Meeting',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      start: '12:00PM',
      end: '3PM',
      date: '2025-01-07',
    },
    {
      id: 5,
      employeeId: 5,
      title: 'Meeting',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      start: '12:00PM',
      end: '3PM',
      date: '2025-01-07',
    },
    {
      id: 6,
      employeeId: 6,
      title: 'Shift',
      start: '12:00PM',
      end: '3PM',
      date: '2025-01-08',
    },
    {
      id: 7,
      employeeId: 8,
      title: 'Training',
      start: '12:00PM',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      end: '7:00 PM',
      date: '2025-01-10',
    },
    {
      id: 8,
      employeeId: 9,
      title: 'Office Work',
      careGiver: 'Dummy Name',
      Patient: 'Patient Dummy',
      start: '12:00PM',
      end: '3PM',
      date: '2025-01-15',
    },
  ]