export const allEvents = [
  {
    id: 1,
    employeeId: 1,
    title: 'Physical Therapy Session',
    careGiver: 'John Smith',
    Patient: 'Emily Brown',
    start: '9:00AM',
    end: '10:30AM',
    date: '2025-01-07',
  },
  {
    id: 2,
    employeeId: 2,
    title: 'Team Meeting',
    careGiver: 'Sarah Johnson',
    Patient: 'N/A',
    start: '2:00PM',
    end: '3:30PM',
    date: '2025-01-09',
  },
  {
    id: 3,
    employeeId: 3,
    title: 'Medication Reminder',
    careGiver: 'Michael Davis',
    Patient: 'James Wilson',
    start: '7:00AM',
    end: '7:30AM',
    date: '2025-01-07',
  },
  {
    id: 4,
    employeeId: 4,
    title: 'Home Safety Inspection',
    careGiver: 'Lisa White',
    Patient: 'Olivia Harris',
    start: '11:00AM',
    end: '12:30PM',
    date: '2025-01-09',
  },
  {
    id: 5,
    employeeId: 5,
    title: 'Caregiver Training Session',
    careGiver: 'Daniel Clark',
    Patient: 'N/A',
    start: '1:00PM',
    end: '4:00PM',
    date: '2025-01-10',
  },
  {
    id: 6,
    employeeId: 6,
    title: 'Routine Check-up',
    careGiver: 'Sophia Martinez',
    Patient: 'Benjamin Taylor',
    start: '10:00AM',
    end: '11:00AM',
    date: '2025-01-08',
  },
  {
    id: 6,
    employeeId: 6,
    title: 'Noon Check-up',
    careGiver: 'Sophia Martinez',
    Patient: 'Benjamin Taylor',
    start: '12:00PM',
    end: '1:00PM',
    date: '2025-01-08',
  },
  {
    id: 6,
    employeeId: 6,
    title: 'Daily Routine Check',
    careGiver: 'Sophia Martinez',
    Patient: 'Benjamin Taylor',
    start: '3:00PM',
    end: '9:00PM',
    date: '2025-01-08',
  },
  {
    id: 7,
    employeeId: 7,
    title: 'Nutritional Counseling',
    careGiver: 'David Lopez',
    Patient: 'Ella Moore',
    start: '3:00PM',
    end: '4:00PM',
    date: '2025-01-15',
  },
  {
    id: 8,
    employeeId: 8,
    title: 'Follow-up Appointment',
    careGiver: 'Emma Thompson',
    Patient: 'Alexander Garcia',
    start: '9:30AM',
    end: '10:15AM',
    date: '2025-01-25',
  },
];



// export const allEvents = [
//     {
//       id: 1,
//       employeeId: 1,
//       title: 'Personal care',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       start: '12:00PM',
//       end: '3:00PM',
//       date: '2025-01-07',
//     },
//     {
//       id: 2,
//       employeeId: 2,
//       title: 'Head Office',
//       start: '2:00AM',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       end: '8:00AM',
//       date: '2025-01-09',
//     },
//     {
//       id: 2,
//       employeeId: 2,
//       title: 'Head Office',
//       start: '2:00AM',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       end: '8:00AM',
//       date: '2025-01-23',
//     },
//     {
//       id: 3,
//       employeeId: 3,
//       title: 'Safe',
//       start: '1:30PM',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       end: '4:30PM',
//       date: '2025-01-07',
//     },
//     {
//       id: 4,
//       employeeId: 4,
//       title: 'Shift',
//       start: '11:00AM',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       end: '12:00PM',
//       date: '2025-01-09',
//     },
//     {
//       id: 5,
//       employeeId: 5,
//       title: 'Meeting',
//       start: '12:00PM',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       end: '3PM',
//       date: '2025-01-07',
//     },
//     {
//       id: 5,
//       employeeId: 5,
//       title: 'Safety Measure',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       start: '12:00PM',
//       end: '3PM',
//       date: '2025-01-07',
//     },
//     {
//       id: 5,
//       employeeId: 5,
//       title: 'Meeting',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       start: '12:00PM',
//       end: '3PM',
//       date: '2025-01-07',
//     },
//     {
//       id: 5,
//       employeeId: 5,
//       title: 'Meeting',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       start: '12:00PM',
//       end: '3PM',
//       date: '2025-01-07',
//     },
//     {
//       id: 6,
//       employeeId: 6,
//       title: 'Shift Details',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       start: '12:00PM',
//       end: '3PM',
//       date: '2025-01-08',
//     },
//     {
//       id: 7,
//       employeeId: 8,
//       title: 'Training',
//       start: '12:00PM',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       end: '7:00 PM',
//       date: '2025-01-10',
//     },
//     {
//       id: 7,
//       employeeId: 8,
//       title: 'Training',
//       start: '12:00PM',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       end: '7:00 PM',
//       date: '2025-01-25',
//     },
//     {
//       id: 8,
//       employeeId: 9,
//       title: 'Office Work',
//       careGiver: 'Dummy Name',
//       Patient: 'Patient Dummy',
//       start: '12:00PM',
//       end: '3PM',
//       date: '2025-01-15',
//     },
//   ]